version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    env_file: .env
  backend:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    env_file: .env
    depends_on:
      - db

